apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
      - name: agent
        image: gcr.io/your-project-id/agent:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: agent-config
        - secretRef:
            name: agent-secrets
