main:
  steps:
  - init:
      assign:
      - agentUrl: ${agent-service-url}
  - callAgent:
      call: http.get
      args:
        url: ${agentUrl}/trigger
      result: agentResponse
  - checkResponse:
      switch:
        - condition: ${agentResponse.status == "success"}
          next: nextStep
        - condition: ${agentResponse.status != "success"}
          next: errorHandler
  - nextStep:
      call: ...
  - errorHandler:
      call: ...
